CREATE TABLE DICIPLINA(
CD_DICIPLINA INT IDENTITY(1111,1) PRIMARY KEY NOT NULL,
NM_DICIPLINA VARCHAR(30) NOT NULL
)
CREATE TABLE DICIPLINA_ESTUDANTE(
ID_DICIPLINA INT NOT NULL,
ID_ESTUDANTE INT NOT NULL,
CONSTRAINT FK_DI FOREIGN KEY(ID_DICIPLINA)REFERENCES DICIPLINA(CD_DICIPLINA),
CONSTRAINT FK_D_E FOREIGN KEY(ID_ESTUDANTE)REFERENCES ESTUDANTE(CD_ESTUDANTE)
)
CREATE TABLE ESTUDANTE(
CD_ESTUDANTE INT IDENTITY(22222,1) PRIMARY KEY NOT NULL,
NM_ESTUDANTE VARCHAR(50) NOT NULL,
E_MAIL VARCHAR(40) NULL
)
CREATE TABLE CEP (
CD_CEP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CEP INT NOT NULL,
RUA VARCHAR(50)NULL,
NUMERO INT NULL,
BAIRRO VARCHAR(20)NULL,
CIDADE VARCHAR(20)NULL,
ESTADO VARCHAR(2),
CD_ESTUDANTE INT NOT NULL,
CONSTRAINT FK_CEP FOREIGN KEY(CD_ESTUDANTE)REFERENCES ESTUDANTE(CD_ESTUDANTE)
)
CREATE TABLE TELEFONE (
CD_TELEFONE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DDD INT NULL,
CD_ESTADO INT NULL,
NUMERO INT NOT NULL,
CD_ESTUDANTE INT NOT NULL,
CONSTRAINT FK_TELEFONE FOREIGN KEY(CD_ESTUDANTE)REFERENCES ESTUDANTE(CD_ESTUDANTE)
)
CREATE TABLE NOTAS(
CD_NOTAS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOTA1 INT NOT NULL,
NOTA2 INT NOT NULL,
NOTA3 INT NOT NULL,
CD_ESTUDANTE INT NOT NULL,
CONSTRAINT FK_NOTAS_E FOREIGN KEY(CD_ESTUDANTE)REFERENCES ESTUDANTE(CD_ESTUDANTE)
)
SELECT ID_DICIPLINA, ID_ESTUDANTE FROM DICIPLINA_ESTUDANTE AS DE
INNER JOIN DICIPLINA AS D ON D.CD_DICIPLINA = DE.ID_DICIPLINA
INNER JOIN ESTUDANTE AS E ON E.CD_ESTUDANTE = DE.ID_ESTUDANTE
INNER JOIN NOTAS AS N ON N.CD_ESTUDANTE= E.CD_ESTUDANTE
where NM_ESTUDANTE='aqui esta'
SELECT NM_ESTUDANTE , CEP , DDD FROM ESTUDANTE AS E
INNER JOIN CEP AS C ON C.CD_ESTUDANTE = E.CD_ESTUDANTE
INNER JOIN TELEFONE AS T ON T.CD_ESTUDANTE = E.CD_ESTUDANTE
WHERE E.CD_ESTUDANTE = 22293
select*from DICIPLINA_ESTUDANTE
select * from TELEFONE
select * from DICIPLINA
insert into DICIPLINA_ESTUDANTE VALUES(1119,22293)
insert into CEP VALUES(0423,'nada',32,'eus','estou','pU',22293)
insert into TELEFONE values (55,11,983982204,22293)
drop table DICIPLINA_ESTUDANTE